name: my_house
description: Mirea project mobile application.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.0-277.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true


  assets:
    - assets/images/

  

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Medium.ttf  
          weight: 500
   
  
