name: my_house
description: Mirea project mobile application.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.0-277.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  provider: ^6.0.5
  auto_route: ^5.0.4
  auto_route_generator: ^5.0.3
  build_runner: ^2.4.1
  google_fonts: ^4.0.3
  dio: ^5.0.2
  shared_preferences: ^2.0.18
  flutter_dotenv: ^5.0.2
  http: ^0.13.5
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - .env

  
