// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFlLgjDsGwcfsVVgP8vGqygi8ELjHfA-A',
    appId: '1:1073961791443:web:d0aa0777d8dd397a69c926',
    messagingSenderId: '1073961791443',
    projectId: 'my-house-11a7b',
    authDomain: 'my-house-11a7b.firebaseapp.com',
    databaseURL: 'https://my-house-11a7b-default-rtdb.firebaseio.com',
    storageBucket: 'my-house-11a7b.appspot.com',
    measurementId: 'G-3QX0213VVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf5vQiWrJ1ja7BUUcPzXRLeeVPVX9sBns',
    appId: '1:1073961791443:android:39420f3db3c16dc469c926',
    messagingSenderId: '1073961791443',
    projectId: 'my-house-11a7b',
    databaseURL: 'https://my-house-11a7b-default-rtdb.firebaseio.com',
    storageBucket: 'my-house-11a7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCALIjkmpCakeziHlukpTivcGXqDs_bJQ',
    appId: '1:1073961791443:ios:112fd77dcab935dc69c926',
    messagingSenderId: '1073961791443',
    projectId: 'my-house-11a7b',
    databaseURL: 'https://my-house-11a7b-default-rtdb.firebaseio.com',
    storageBucket: 'my-house-11a7b.appspot.com',
    iosClientId: '1073961791443-d3l076vo03d9u6brddlh1k2t3f9m8np4.apps.googleusercontent.com',
    iosBundleId: 'com.example.myHouse',
  );
}
